config/routes.rb
Rails.application.routes.draw do

  # Service Worker
  get '/service-worker', to: "application#service_worker", format: :js

  # Static routes
  get '/geolocation', to: "application#geolocation", as: :geolocation
  get '/notifications', to: "application#notifications", as: :notifications

  # Users 
  devise_for :users, controllers: {
    sessions: 'user/sessions'
  }
  
  # Koi Assets and Uploads
  resources :uploads do
    post :image, on: :collection
  end
  resources :documents, only: [:show]
  resources :images, only: [:show]
  resources :assets, only: [:show]

  # Koi pages and modules 
  resources :pages, only: [:index, :show], as: :koi_pages

  # Homepage 
  root to: 'pages#index'

  # Koi Namespace 
  mount Koi::Engine => "/admin", as: "koi_engine"

  # Fallback pages routes 
  get "/:id"  => "pages#show", as: :page
end

app/views/layouts/_analytics.html.erb
<%- ga_key = get_koi_site_setting("site.google_analytics.profile_id") -%>
<%- if ga_key -%>
  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', '<%= ga_key -%>', 'auto');
    <%= yield :custom_ga -%>
    if(!Ornament.features.turbolinks) {
      ga('send', 'pageview');
    }
  </script>
<%- end -%>

app/views/layouts/_seo.html.erb
<%-

  cache_version ||= "1"
  koi_settings ||= true

  # Defaults 
  seo_title ||= "KoiPWA Sandbox"
  seo_title_postfix ||= seo_title
  seo_keywords ||= false
  seo_description ||= ""
  seo_image ||= false # "#{root_url}assets/share.png?v=#{cache_version}"

  # Twitter Settings
  twitter_handle ||= ""
  twitter_creator ||= ""

  # Koi Site Settings 
  if defined?(Translation) && koi_settings 
    koi_title = Translation.find_by_key('site.title').try(:value)
    koi_description = Translation.find_by_key('site.meta_description').try(:value)
    koi_keywords = Translation.find_by_key('site.meta_keywords').try(:value)
    site_settings_title = clean_share_input(koi_title) if koi_title
    site_settings_meta = clean_share_input(koi_description) if koi_description
    site_settings_keywords = clean_share_input(koi_keywords) if koi_keywords
    seo_title = site_settings_title
    seo_title_postfix = seo_title
  end

  # Page Title
  if !seo("title").blank?
    seo_title = seo("title")
  elsif content_for?(:page_title)
    seo_title = yield(:page_title)
  elsif content_for?(:title)
    seo_title = yield(:title)
  elsif content_for?(:og_title)
    seo_title = yield(:og_title)
  end

  # Append | <postfix> to the end of title if necessary
  if !seo_title_postfix.blank? && !seo_title.include?(seo_title_postfix)
    seo_title = raw "#{seo_title} - #{seo_title_postfix}"
  end

  # Meta Description
  if !seo("meta_description").blank?
    seo_description = clean_share_input(seo('meta_description'))
  elsif content_for?(:og_description) 
    seo_description = yield(:og_description)
  elsif site_settings_meta.present?
    seo_description = clean_share_input(site_settings_meta)
  end

  # Meta Keywords
  if !seo("meta_keywords").blank?
    seo_keywords = clean_share_input(seo('meta_keywords'))
  elsif site_settings_keywords.present?
    seo_keywords = clean_share_input(site_settings_keywords)
  end

  # Meta Image
  if content_for?(:meta_image)
    seo_image = yield(:meta_image)
  end

  # Facebook Title
  if content_for?(:og_title) 
    facebook_title = yield(:og_title)
  else
    facebook_title = seo_title
  end

  # Facebook description
  if content_for?(:og_description)
    facebook_description = yield(:og_description)
  else
    facebook_description = seo_description
  end

  # Facebook author
  facebook_author = content_for?(:og_author) ? yield(:og_author) : false

  # Facebook publish time
  facebook_publish_time = content_for?(:og_publish_time) ? yield(:og_publish_time) : false

  # Facebook image
  if content_for?(:og_image)
    facebook_image = yield(:og_image)
  elsif content_for?(:meta_image)
    facebook_image = yield(:meta_image)
  else
    facebook_image = seo_image
  end

  # Twitter Image
  if content_for?(:twitter_image)
    twitter_image = yield(:twitter_image)
  elsif content_for(:og_image)
    twitter_image = yield(:og_image)
  elsif content_for(:meta_image)
    twitter_image = yield(:meta_image)
  else
    twitter_image = seo_image
  end

  # Add base URL to facebook image
  facebook_image = absolute_url(facebook_image)

  # Add base URL to twitter image
  twitter_image = absolute_url(twitter_image)

-%>

<title><%= seo_title -%></title>
<meta name="description" content="<%= raw seo_description %>">
<%- if seo_keywords -%>
  <meta name="keywords" content="<%= raw seo_keywords %>">
<%- end -%>
<%- if facebook_image -%>
  <link rel="image_src" href="<%= facebook_image -%>" />
<%- end -%>

<!-- FACEBOOK -->
<%- if facebook_image && !content_for?(:disable_og_image) -%>
  <meta property="og:image" content="<%= facebook_image -%>" />
<%- end -%>
<meta property="og:title" content="<%= facebook_title -%>" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:description" content="<%= raw facebook_description -%>">
<%- if facebook_author -%>
  <meta property="og:author" content="<%= facebook_author -%>" />
<%- end -%>
<%- if facebook_publish_time -%>
  <meta property="og:published_time" content="<%= facebook_publish_time -%>" />
<%- end -%>

<!-- TWITTER -->
<meta name="twitter:card" content="summary" />
<%- unless twitter_handle.blank? -%>
  <meta name="twitter:site" content="<%= twitter_handle -%>" />
<%- end -%>
<%- unless twitter_image.blank? -%>
  <meta name="twitter:image" content="<%= twitter_image -%>" />
<%- end -%>
<%- unless twitter_creator.blank? -%>
  <meta name="twitter:creator" content="<%= twitter_creator -%>">
<%- end -%>
<meta name="twitter:title" content="<%= seo_title -%>">
<meta name="twitter:url" content="<%= request.original_url %>">
<meta name="twitter:description" content="<%= raw seo_description -%>">

app/views/layouts/_webfonts.html.erb
<%- config ||= {
  google: {
    families: ['Open Sans:400,700,400italic,700italic'],
  }
} -%>

<%- if config -%>
  <script>
    WebFontConfig = <%= raw config.to_json -%>;
    (function(d) {
      var wf = d.createElement('script'), s = d.scripts[0];
      wf.src = 'https://ajax.googleapis.com/ajax/libs/webfont/1.6.16/webfont.js';
      s.parentNode.insertBefore(wf, s);
    })(document);
  </script>
<%- end -%>

app/views/layouts/application.html.erb
<% content_for :global do %>

  <%- content_for :page_main do -%>
    <% if content_for? :title %>
      <h1 class="heading-one page--title">
        <%= yield :title %>
      </h1>
    <% end %>
    <%= content_for?(:application) ? yield(:application) : yield %>
  <%- end -%>

  <%- if content_for? :sidebar -%>
    <div class="page__with-sidebar">
      <div class="page--main">
        <%= yield :page_main -%>
      </div>
      <div class="page--sidebar">
        <%= yield :sidebar -%>
      </div>
    </div>
  <%- elsif content_for? :sidebar_right -%>
    <div class="page__with-sidebar-right">
      <div class="page--main">
        <%= yield :page_main -%>
      </div>
      <div class="page--sidebar">
        <%= yield :sidebar_right -%>
      </div>
    </div>
  <%- else -%>
    <%= yield :page_main -%>
  <%- end -%>  
  
<% end %>

<%= render :file => "layouts/global" %>

app/views/layouts/global.html.erb
<!DOCTYPE html>
<html lang="en">
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# website: http://ogp.me/ns/website#">

    <%# Meta tags %>
    <meta charset="utf-8"/>
    <%= render "layouts/seo" -%>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <% unless Rails.env == "production" %>
      <meta name="robots" content="noindex,nofollow"/>
    <% end  %>
    <%= yield :meta %>

    <script>
      Ornament = window.Ornament || {};
      // dataLayer = window.dataLayer = {};
    </script>

    <%# Styles %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= yield :styles %>

    <%# Scripts %>
    <%= javascript_include_tag "ornament/vendor" %>
    <%= javascript_include_tag "application" %>
    <%= yield :scripts %>

    <%# Google Tag Manager - GTM-XXXXXXX %>
    <%- gtm_code = get_koi_site_setting("site.gtm_code") -%>
    <%- if gtm_code -%>
      <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','<%= gtm_code -%>');</script>
    <%- end -%>

    <%# Webfonts %>
    <%#= render "layouts/webfonts", config: {
      google: {
        families: ['Open Sans:400,700,400italic,700italic'],
      }
    } -%>

    <%# Koi Scripts %>
    <%- koi_scripts = get_koi_site_setting("site.head_scripts") -%>
    <%= koi_scripts if koi_scripts -%>

    <% if user_signed_in? %>
      <script>
        Ornament.User = {
          id: <%= current_user.id %>
        }
      </script>
    <% end %>

  </head>

  <body class="styleguide <%= yield :body_class -%>"> 
    <%- if gtm_code -%>
      <%# Google Tag Manager (noscript Version) %>
      <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=<%= gtm_code -%>" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <%- end -%>

    <a class="skip-link" href="#main">skip to content</a>

    <div class="layout tray-container" data-tray-layout>

      <div class="tray" data-tray>
        <nav aria-label="Global Navigation" role="navigation">
          <ul>
            <li>Mobile menu TBD</li>
          </ul>
        </nav>
      </div>

      <div class="tray--page layout--content environment-<%= Rails.env -%>" data-tray-page>

        <header class="header" role="banner">
          <div class="layout--container">
            <h1 class="header--logo heading-four">
              <%= link_to "KoiPWA Sandbox", root_path -%>
            </h1>
            <button class="header--menu" aria-label="Toggle menu" data-tray-anchor>
              <%= icon("hamburger", fill: "#ffffff", width: 25, height: 23) -%>
            </button>
          </div>
        </header>

        <div data-layout-positioner class="layout--positioner tray--open-overlay">
          <div class="offline-notification panel__flash panel__alert" data-offline-notification>
            <div class="layout--container">
              <strong>You are currently offline.</strong>
            </div>
          </div>
          <div class="header--navigation navigation">
            <div class="layout--container">
              <nav role="navigation">
                <%= koi_render_navigation "header_nav", 
                  "header_navigation", 
                  renderer: :ornament_menu, 
                  level: 1..2, 
                  expand_all: true, 
                  id_namespace: "header",
                  dom_class: '',
                  pre_items: [{
                    key: "login",
                    name: "Login",
                    url: new_user_session_path,
                    html_options: {
                      data: {
                        user_login: ""
                      }
                    }
                  }]
                %>
                <% if false %>
                  <ul>
                    <li><%= link_to "Koi Pages", koi_pages_path -%></li>
                    <li><%= link_to "Geo", geolocation_path %></li>
                    <li><%= link_to "Notifications", notifications_path %></li>
                    <%- if user_signed_in? -%>
                      <li><%= link_to "Log Out", destroy_user_session_path, method: :delete, data: { user_logout: "" } -%></li>
                    <%- else -%>
                      <li><%= link_to "Log In", new_user_session_path, data: { user_login: "" } -%></li>
                      <li><%= link_to "Register", new_user_registration_path, data: { user_register: "" } -%></li>
                    <%- end -%>
                  </ul>
                <% end %>
              </nav>
            </div>
          </div>
          <%= render "/shared/oldie" -%>
          <%= yield :above_layout -%>
          <%= render "/shared/flash" -%>
          <%- if content_for?(:global) || !yield.blank? -%>
            <a id="main" name="main" tabindex="-1"></a>
            <main class="layout--main <%= yield(:layout_class) -%>" role="main">
              <div class="layout--container">
                <%= content_for?(:global) ? yield(:global) : yield %>
              </div>
            </main>
          <%- end -%>
          <%= yield :below_layout -%>
          <footer class="footer" role="contentinfo">
            <div class="layout--container">
              <button data-webshare>Share this page</button>
              <%= render layout: "shared/inline_lightbox", locals: { inline_id: "share" } do -%>
                <div class="panel--padding spacing">
                  Generic share fallback
                </div>
              <%- end -%>
            </div>
          </footer>
        </div>
      </div>

    </div>

    <%= yield :scripts_bottom %>
    
    <%= render "layouts/analytics" -%>

    <div data-ornament-icons>
      <div data-ornament-icon="chevron-left"><%= icon("chevron_left") -%></div>
      <div data-ornament-icon="chevron-right"><%= icon("chevron_right") -%></div>
      <div data-ornament-icon="close"><%= icon("close") -%></div>
      <div data-ornament-icon="spinner"><%= icon("spinner") -%></div>
    </div>

    <div data-credentials-modals>
      <%= render layout: "shared/inline_lightbox", locals: { inline_id: "user-login" } do -%>
        <div class="panel--padding spacing">
          <h2 class="heading-four">Login to KoiPWA</h2>
          <%= render "/users/sessions/form" -%>
        </div>
      <%- end -%>
      <%= render layout: "shared/inline_lightbox", locals: { inline_id: "user-register" } do -%>
        <div class="panel--padding spacing">
          <h2 class="heading-four">Register new user account for KoiPWA</h2>
          <%= render "/users/registrations/form" -%>
        </div>
      <%- end -%>
    </div>

  </body>

</html>